# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: msg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmsg.proto\"\x07\n\x05\x45mpty\"\xbd\x01\n\x0b\x43hatMessage\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_user_id\x18\x02 \x01(\t\x12\x12\n\nto_user_id\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x05 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x06 \x01(\t\x12\x13\n\x0b\x63ontent_url\x18\x07 \x01(\t\x12\x0f\n\x07\x63\x61ption\x18\x08 \x01(\t\x12\x10\n\x08hotel_id\x18\t \x01(\t2[\n\nChatServer\x12$\n\nChatStream\x12\x06.Empty\x1a\x0c.ChatMessage0\x01\x12\'\n\x0fSendChatMessage\x12\x0c.ChatMessage\x1a\x06.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=13
  _globals['_EMPTY']._serialized_end=20
  _globals['_CHATMESSAGE']._serialized_start=23
  _globals['_CHATMESSAGE']._serialized_end=212
  _globals['_CHATSERVER']._serialized_start=214
  _globals['_CHATSERVER']._serialized_end=305
# @@protoc_insertion_point(module_scope)
